[mongodb]
mongodb-dev.laddudevops86.fun

[catalogue]
catalogue-dev.laddudevops86.fun

[redis]
redis-dev.laddudevops86.fun

[user]
user-dev.laddudevops86.fun

[cart]
cart-dev.laddudevops86.fun

[mysql]
mysql-dev.laddudevops86.fun

[shipping]
shipping-dev.laddudevops86.fun

[rabbitmq]
rabbitmq-dev.laddudevops86.fun

[payment]
payment-dev.laddudevops86.fun

[frontend]
frontend-dev.laddudevops86.fun


[all:vars]
ansible_user=ec2-user
ansible_password=DevOps321
MONGODB_HOST=mongodb-dev.laddudevops86.fun
CATALOGUE_HOST=catalogue-dev.laddudevops86.fun
REDIS_HOST=redis-dev.laddudevops86.fun
USER_HOST=user-dev.laddudevops86.fun
CART_HOST=cart-dev.laddudevops86.fun
MYSQL_HOST=mysql-dev.laddudevops86.fun
SHIPPING_HOST=shipping-dev.laddudevops86.fun
RABBITMQ_HOST=rabbitmq-dev.laddudevops86.fun
PAYMENT_HOST=payment-dev.laddudevops86.fun


