[local]
localhost

[mongodb]
mongodb-dev.laddudevops86.fun

[catalogue]
catalogue-dev.laddudevops86.fun

[redis]
redis-dev.laddudevops86.fun

[user]
user-dev.laddudevops86.fun

[cart]
cart-dev.laddudevops86.fun

[mysql]
mysql-dev.laddudevops86.fun

[shipping]
shipping-dev.laddudevops86.fun

[rabbitmq]
rabbitmq-dev.laddudevops86.fun

[payment]
payment-dev.laddudevops86.fun

[frontend]
frontend-dev.laddudevops86.fun